### ISSUE TITLE
Add new utilities and plotting tools

### ISSUE THREAD

**Issue by gaffarelj** [tudat-team/tudatpy#42]
New plotting tools and utilities could be added asap, so they are ready for students before they start the P&O course.

Here is the current list of tools to be added:

**Plotting:**
- [x] Add a function to create `matplotlib` plots with a dual y-axis (#31)
- [x] Add a function to create 3D `matplotlib` plots to show the trajectory of different bodies (#32)
- [x] Add a function to create `matplotlib` plots comparing two objectives, adding a Pareto front, and possibly a third objective through a colormap (#43).
- [ ] Add a function to plot the position history (in 2D or 3D), with the velocity history as vectors going from each point (to show at each moment where the vehicle is going), and optionally the orientation of the vehicle (#64)

**Utilities:**
- [x] Mute any terminal messages when enclosed by a _with_ statement (#29)
- [x] Add a tool to compare states and dependent variable histories interpolated over time (#27)
- [x] Add a function to return a boolean mask stating whether each multi-dimensional point in a set is a Pareto optimum (#30)

**User guide:**
- [ ] In addition, some content on the use of `matplotlib` for post-processing can be added to the user guide (#41).

**Comment by gaffarelj** [comment]
@DominicDirkx @FilippoOggionni @jo11he @transferorbit : please all feel free to add your suggestions and thoughts on this.
